### ISSUE TITLE
svg file names being padded with leading zeros

### ISSUE THREAD

**Issue by russormes** [banyan/react-emoji#16]
Hi, 

Thanks for the module, we are using in it on our chat app. 

I am getting 404 errors for any emoticon that has an svg file name with only two numbers befoe the '-' in the file name, for example 23-20e3.svg (:hash:). 

This is being rendered into the HTML with the following url: 
https://twemoji.maxcdn.com/svg/0023-20e3.svg

As you can see the file name is now 0023-20e3.svg and so the resource is not found. I tested with other filename with the same structure xx-xxxx.svg and they all have the same issue. 

xxxx.svg works fine.

**Comment by khardenstine** [comment]
Seeing this too for copyright and registered emojis too.

react-emoji uses https://github.com/banyan/emoji-annotation-to-unicode for building a name/unicode mapping.  That project just parses the GitHub API to generate its mappings, which is clearly not 1 for 1 compatible with twemoji.

I would assume a find on https://api.github.com/emojis for "/0" would list all the broken ones.
