### ISSUE TITLE
If emojify function param is invalid 'Uncaught TypeError' is thrown

### ISSUE THREAD

**Issue by jnwelzel** [banyan/react-emoji#4]
If I pass ":fu:" to emojify function for example, all I get is a "Uncaught TypeError: Cannot read property 'toUpperCase' of null" in my face. Is there a way to maybe make it fail more gracefully? Maybe just render the param that was passed (":fu:" in this case)? I'm using the emojione icons btw. When using twitter ones I get a broken image icon displayed instead. Again, would be better to just get the string param rendered imho.

Thanks
Great mixin :)

**Comment by banyan** [comment]
@jnwelzel 

Thanks for the catch! :bow: I haven't noticed when emoji only for used in GitHub returns `null` such as :fu: :octocat:. Changed the behavior to return simply string param as you said. Thanks!
